name = "scalarConservationLaws"
uuid = "4a2f1122-f3a3-49e8-98c4-2ac24fe47f52"
authors = ["Felix Benning <felix.benning@gmail.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
